Added new internal ecr repo module for shared services.
ministryofjustice/modernisation-platform pull request #1120
Opened 2021-09-23 15:01 UTC by ezman

Added new internal ecr repo module for shared services.

First implementation for performance-hub.

TODO: Account lookup is failing. Using defaults for now.

2021-09-23 15:02 UTC, zuriguardiola approved these changes

2021-09-23 15:07 UTC, zuriguardiola approved these changes

2021-09-23 15:58 UTC, davidkelliott approved these changes
LGTM

2021-09-23 15:59 UTC, davidkelliott requested changes
Aha sorry actually could we fix the static code analysis warnings first please 🙏  thanks

2021-09-24 07:53 UTC, davidkelliott approved these changes
Thanks!

2021-09-24 13:36 UTC, pete-j-g approved these changes

2021-09-24 13:36 UTC, merged