Nomis production firewall changes
ministryofjustice/modernisation-platform pull request #1698
Opened 2022-04-21 10:34 UTC by SteveLinden

Put in production firewall changes for Nomis.
Also added nomis-production to hmpps-production.json where it had been missed.

2022-04-21 11:00 UTC, dms1981 commented on terraform/environments/core-network-services/firewall.tf
> +          priority = 100
This probably needs changing as it will conflict with an earlier rule that's got the same priority

2022-04-21 11:01 UTC, dms1981 requested changes
I think you'll want to check your rule priorities here to align them with the priorities that have already been set

2022-04-22 08:41 UTC, zuriguardiola approved these changes

2022-04-22 12:26 UTC, dms1981 approved these changes

2022-04-22 12:33 UTC, merged