Adding dms:* permissions.
ministryofjustice/modernisation-platform pull request #2651
Opened 2022-11-15 16:38 UTC by ep-93

Requested in the ask mod platform channel.

2022-11-15 16:44 UTC, ewastempel approved these changes

2022-11-16 08:16 UTC, julialawrence requested changes

2022-11-16 08:16 UTC, julialawrence commented on terraform/environments/bootstrap/delegate-access/iam.tf
> +      "dms:*",
Based on the error Hari's having, I think this needs to go into MemberInfrastructureAccess role policy. I believe this is adding it to the collaborator developer role.

2022-11-16 08:16 UTC, julialawrence commented on terraform/environments/bootstrap/delegate-access/iam.tf
> +      "dms:*",
This is the policy it should be in: https://github.com/ministryofjustice/modernisation-platform/blob/2e9230ba53ae225bcb0d6b956a4c5f975a7677c6/terraform/environments/bootstrap/delegate-access/iam.tf#L45

2022-11-16 09:11 UTC, davidkelliott approved these changes

2022-11-16 09:13 UTC, julialawrence approved these changes

2022-11-16 09:15 UTC, merged