ARN required not json, missed by myself. Tested.
ministryofjustice/modernisation-platform pull request #2871
Opened 2022-12-20 17:06 UTC by ep-93

2022-12-20 17:30 UTC, ep-93 commented on terraform/environments/bootstrap/delegate-access/iam.tf
> +  policy_arn                  = aws_iam_policy.execution-combined-policy.arn
@davidkelliott I missed the arn here and supplied json... even though it said arn... not sure what I was thinking!

2022-12-21 09:06 UTC, davidkelliott requested changes
Few minor things but other than that I think it looks good 👍

2022-12-21 09:06 UTC, davidkelliott commented on terraform/environments/bootstrap/delegate-access/iam.tf
> +resource "aws_iam_policy" "execution-combined-policy" {
Are the cloudformation permissions needed? (in the json above, sorry didn't review this one before :) )

2022-12-21 09:06 UTC, davidkelliott commented on terraform/environments/core-shared-services/iam.tf
> +  name        = "SSM-Automation-Execution-Combined-Policy"
Is this the correct name?  Looks like a copy and paste from above

2022-12-21 09:06 UTC, davidkelliott commented on terraform/environments/core-shared-services/iam.tf
> +  description = "Combined policy for SSM Automation Execution"
As above copy and paste

2022-12-21 09:40 UTC, davidkelliott approved these changes
Thanks 👍

2022-12-21 09:59 UTC, merged