Initial code for TGW Flow logs
ministryofjustice/modernisation-platform pull request #2950
Opened 2023-01-10 16:45 UTC by markgov

code still needs to be tested do not merge

2023-01-12 12:17 UTC, davidkelliott requested changes

2023-01-12 12:17 UTC, davidkelliott commented on terraform/environments/core-network-services/locals.tf
> +  active_tgw_all_attachments = [
Could we get this list dynamically so we don't need to manually update it?  It might need to be a concat of a few different things

2023-01-12 13:44 UTC, dms1981 approved these changes

2023-01-12 13:59 UTC, davidkelliott approved these changes

2023-01-12 14:00 UTC, davidkelliott requested changes
Could you resolve the SCA warnings please?

2023-01-13 09:34 UTC, davidkelliott approved these changes
Looks good to me! 👏 First PR on MP!

2023-01-13 09:47 UTC, merged