Intial commit for adding a database user / policy.
ministryofjustice/modernisation-platform pull request #3087
Opened 2023-02-07 15:02 UTC by ep-93

2023-02-08 11:45 UTC, davidkelliott commented
@ep-93 here is a previous PR adding a migration role in case this helps cover all the areas where changes are needed https://github.com/ministryofjustice/modernisation-platform/pull/2888/files

2023-02-10 09:33 UTC, davidkelliott requested changes

2023-02-10 09:33 UTC, davidkelliott commented on terraform/environments/bootstrap/single-sign-on/main.tf
> +  name         = "modernisation-platform-database-mgmt"
The SSO plan is failing as the name is too long, maybe rename to mp-instance-management ?

2023-02-10 09:33 UTC, davidkelliott commented on terraform/environments/bootstrap/delegate-access/policies.tf
> +  statement {
I think this statement should be removed as it's probably too excessive for this role

2023-02-10 11:39 UTC, SteveLinden reviewed
There's a double "/" on one line. Probably not an issue but it might be worth checking. I suspect it's because of copy and paste
source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"

2023-02-13 10:54 UTC, davidkelliott commented on terraform/environments/bootstrap/delegate-access/policies.tf
> +      "ec2:Start-s",
Is this change intentional?

2023-02-14 08:57 UTC, davidkelliott approved these changes
Looks good, just double check the sprinkler plan runs fine before merging once the AWS root account changes have been deployed.

2023-02-14 09:19 UTC, merged