Intial plan for certificates giving all access to developers
ministryofjustice/modernisation-platform pull request #3721
Opened 2023-04-25 13:49 UTC by SteveLinden

This is the initial code to add certificate access to developers. It doesn't currently restrict based on developers area so raised as a draft to look at and confirm it looks correct. Based on json code from AWSCertificateManagerFullAccess. A couple of bits had to be removed as they caused the plan to fail (e.g. Resource": "arn:aws:iam::*:role/aws-service-role/acm.amazonaws.com/AWSServiceRoleForCertificateManager*").

Second iteration was to remove all that code as the acm  "acm:ImportCertificate" was already in place but doesn't allow the addition of tags so  "acm.AddTagsToCertificate" as included.

2023-04-27 16:06 UTC, ep-93 approved these changes
LGTM

2023-04-27 16:44 UTC, davidkelliott requested changes

2023-04-27 16:44 UTC, davidkelliott commented on terraform/environments/bootstrap/delegate-access/policies.tf
> +      "acm.AddTagsToCertificate",
```suggestion
      "acm:AddTagsToCertificate",
```
Small typo :)

2023-04-28 09:10 UTC, davidkelliott approved these changes
👍 👏

2023-04-28 09:14 UTC, merged