Feature/pagerduty firewall dropped
ministryofjustice/modernisation-platform pull request #4046
Opened 2023-05-26 12:47 UTC by ep-93

Added SNS topic and now reference it.

2023-05-26 14:03 UTC, davidkelliott requested changes

2023-05-26 14:03 UTC, davidkelliott commented on terraform/environments/core-network-services/monitoring.tf
> +  provider = aws.eu-west-2
You can remove this provider block and use the default provider

2023-05-26 14:03 UTC, davidkelliott commented on terraform/environments/core-network-services/monitoring.tf
> +  providers = {
Same here, provider block can be removed

2023-05-30 10:43 UTC, SteveLinden approved these changes

2023-05-30 10:51 UTC, merged