pager duty changes
ministryofjustice/modernisation-platform pull request #4245
Opened 2023-06-14 14:27 UTC by markgov

This PR covers work for issue [Define pagerduty slack integrations in code#4154](https://github.com/ministryofjustice/modernisation-platform/issues/4154) where we are trying to automate the integration of a slack channel to a pager duty sevice

2023-06-14 14:47 UTC, SteveLinden approved these changes

2023-06-14 14:52 UTC, davidkelliott requested changes
Some minor formatting changes please just to keep the code tidy other than that it looks good 👍

2023-06-14 14:52 UTC, davidkelliott commented on terraform/pagerduty/member-services-integrations.tf
> +
```suggestion
```

2023-06-15 08:20 UTC, davidkelliott approved these changes

2023-06-15 08:21 UTC, merged