Update Kinesis Permissions for Reporting Policy
ministryofjustice/modernisation-platform pull request #4352
Opened 2023-06-19 11:45 UTC by harichintala1

- Add kinesis Read, List
- Add Kinesis Put Permissions

2023-06-19 11:49 UTC, dominic-messenger-moj submitted a review, later dismissed

2023-06-19 12:03 UTC, ep-93 approved these changes

2023-06-19 12:05 UTC, ep-93 requested changes
SCA failing, looking into why

2023-06-21 08:57 UTC, ep-93 approved these changes

2023-06-21 08:57 UTC, merged