Create account creation and network files for Performance Hub.
ministryofjustice/modernisation-platform pull request #636
Opened 2021-05-06 10:39 UTC by zuriguardiola

Amend cidr-allocation file to allocate CIDRs required for a new Performance Hub account. Add new account and networking json files to create account, set up security baselines, and networking once PR is merged.

2021-05-06 10:42 UTC, donmasters approved these changes
LGTM

2021-05-06 10:48 UTC, donmasters requested changes

2021-05-06 10:48 UTC, donmasters commented on environments-networks/hmpps-preproduction.json
> +    "transit_gateway": "10.233.0.128/26",
Is this number correct ?

2021-05-06 11:20 UTC, zuriguardiola commented on environments-networks/hmpps-preproduction.json
> +    "transit_gateway": "10.233.0.128/26",
Just changed it to the correct CIDR

2021-05-06 12:20 UTC, donmasters submitted a review, later dismissed
LGTM

2021-05-12 09:24 UTC, donmasters approved these changes
LGTM

2021-05-12 15:12 UTC, philhorrocks approved these changes

2021-05-12 15:13 UTC, merged