Update ad-fixngo.tf
ministryofjustice/modernisation-platform pull request #6366
Opened 2024-03-01 07:56 UTC by ep-93

## A reference to the issue / Description of it

{Please write here}

## How does this PR fix the problem?

{Please write here}

## How has this been tested?

Please describe the tests that you ran and provide instructions to reproduce.

{Please write here}

## Deployment Plan / Instructions

Will this deployment impact the platform and / or services on it?

{Please write here}

## Checklist (check `x` in `[ ]` of list items)

- [ ] I have performed a self-review of my own code
- [ ] All checks have passed
- [ ] I have made corresponding changes to the documentation
- [ ] Plan and discussed how it should be deployed to PROD (If needed)

## Additional comments (if any)

{Please write here}

2024-03-01 08:21 UTC, SteveLinden approved these changes

2024-03-01 16:45 UTC, drobinson-moj approved these changes

2024-03-01 16:54 UTC, drobinson-moj requested changes
Sorry - just realised there is a bug and applying will zap the EC2.  Any chance I can get a fix in first...

2024-03-04 08:19 UTC, dms1981 approved these changes

2024-03-04 09:19 UTC, drobinson-moj approved these changes

2024-03-04 09:45 UTC, merged