Athena automation
ministryofjustice/modernisation-platform pull request #950
Opened 2021-08-02 08:31 UTC by philhorrocks

Athena Added lambda to setup:
   -  Athena database
   - Athena table
   - Gets list of AWS mod platform accounts to populate Athena schema  

Added Terraform to automate the the build and deployment of the the lambda and setup to associated IAM role for access to Athena and Secrets Manager

2021-08-02 08:41 UTC, ezman commented on terraform/environments/core-logging/lambda/index.py
> +    print("[+] Creating Athena database" + athena_db)
Might need an extra space.

2021-08-02 08:43 UTC, ezman approved these changes
LGTM

2021-08-02 08:54 UTC, davidkelliott requested changes
Hi Phil could you have a look at some of the issues the linter has picked up and see if any of them are valid?  Some of them around encryption etc look relevant (some will be for the existing logging infrastructure as the scan runs on the whole core-logging folder). If the checks are completely irrelevant you can add an ignore comment in for tfsec,checkov or tflint as appropriate.  Don't worry about fixing everything now we need to take a bit of time to go through all our existing code at some point but it would be good to keep anything new we create in check. Thanks
Thanks.

2021-08-11 09:06 UTC, philhorrocks commented
needs to rebase

2021-08-11 09:06 UTC, closed without merging